[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://connect.facebook.net https://cdn.jsdelivr.net;
    style-src  'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://cdnjs.cloudflare.com;
    font-src   'self' https://fonts.gstatic.com https://cdn.jsdelivr.net data:;
    img-src    'self' data: https://www.facebook.com https://randomuser.me https://upload.wikimedia.org;
    connect-src 'self' https://graph.facebook.com https://randomuser.me https://www.facebook.com;
    base-uri 'self';
    frame-ancestors 'none';
  """
